[package]
name = "rusb"
version = "0.5.2"
authors = ["David Cuddeback <david.cuddeback@gmail.com>", "Ilya Averyanov <a1ien.n3t@gmail.com>"]
description = "Rust library for accessing USB devices."
license = "MIT"
homepage = "https://github.com/a1ien/rusb"
repository = "https://github.com/a1ien/rusb.git"
readme = "README.md"
keywords = ["usb", "libusb", "hardware", "bindings"]
edition = "2018"

[badges]
travis-ci = { repository = "a1ien/rusb" }

[features]
asynchronous = []

[dependencies]
bit-set = "0.5.0"
libusb1-sys = "0.3.0"
libc = "0.2"

[dev-dependencies]
regex = "0.1"
